try {
  console.log(123)
} catch(e) {}